<<<<<<< HEAD
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 6.0.4 on 2026-04-11 07:37

import django.db.models.deletion
from django.db import migrations, models
>>>>>>> 09e00d1cf6dd864884eaa763c717b51140f287db


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
<<<<<<< HEAD
                ('id',           models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title',    models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('job_url',      models.URLField(blank=True)),
                ('saved_date',   models.DateField(auto_now_add=True)),
                ('notes',        models.TextField(blank=True)),
                ('applicant',    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='accounts.applicant')),
            ],
            options={'ordering': ['-saved_date']},
        ),
    ]
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('job_url', models.URLField(blank=True, help_text='Link to the job posting')),
                ('saved_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='accounts.applicant')),
            ],
            options={
                'ordering': ['-saved_date'],
            },
        ),
    ]
>>>>>>> 09e00d1cf6dd864884eaa763c717b51140f287db
