# Generated by Django 4.2.30 on 2026-05-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interview_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together={('applicant_name', 'interview_date', 'interview_type', 'interviewer')},
        ),
    ]
