# Generated by Django 6.0.4 on 2026-04-11 06:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='employer',
            name='date_registered',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='posting_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.jobcategory'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='employer.employer'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.jobtitle'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employer.jobcategory'),
        ),
        migrations.AlterModelTable(
            name='employer',
            table='employer_employer',
        ),
        migrations.AlterModelTable(
            name='jobcategory',
            table='employer_jobcategory',
        ),
        migrations.AlterModelTable(
            name='jobposting',
            table='employer_jobposting',
        ),
        migrations.AlterModelTable(
            name='jobtitle',
            table='employer_jobtitle',
        ),
    ]
