# Generated by Django 6.0.4 on 2026-04-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('AdminID', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeNumber', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=100)),
                ('DateAssigned', models.DateField()),
                ('PermissionsLevel', models.IntegerField()),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('LogID', models.AutoField(primary_key=True, serialize=False)),
                ('ActionTaken', models.CharField(max_length=255)),
                ('EntityAffected', models.CharField(max_length=255)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auditlog',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('NotificationID', models.AutoField(primary_key=True, serialize=False)),
                ('MessageContent', models.TextField()),
                ('SentDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
